
CFLAGS = -Wall -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -g -O3

read_image: read_image.c
	gcc $(CFLAGS) read_image.c -o read_image -lm

clean:
	rm -f read_image

